### PR TITLE
105 update meshkernel api calls to version 300

### LINKED ISSUE #105: Update meshkernel API calls to version 3.0.0
### Kind of request

Changing existing functionality

### Enhancement Description

With the upcoming release of meshkernel 3.0.0, there are some API calls in meshgeneration that need to be updated. Since we depend on hydrolib-core, the [569-bumping-meshkernel-version-to-latest-v300](https://github.com/Deltares/HYDROLIB-core/tree/569-bumping-meshkernel-version-to-latest-v300) branch can be used to test with the version of hydrolib-core that has update API calls. This branch is work in progress though. An overview of API changes is available in this issue and its comments: https://github.com/Deltares/dfm_tools/issues/563

Additionally:
- [x] update minimal meshkernel version in pyproject.toml >=3.0.0
- [x] update env for github testing
- [ ] revert hydrolib-core and xugrid git link in pyproject.toml and env files
- [ ] this might be a good chance to move hydrolib-core mesh generation to meshkernel calls from hydromt_delft3dfm directly

### Use case

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by veenstrajelmer**
## Issue addressed
Fixes #105

## Explanation
There were major hydrolib-core changes to facilitate meshkernel 3.0.0. Actually it was based on meshkernel 2.0.2, so it makes sense that it could not work with meshkernel 2.1.0. The hydrolib-core PR contains all changes: https://github.com/Deltares/HYDROLIB-core/pull/574/files

## Checklist
- [ ] ~Updated tests or added new tests~
- [x] Branch is up to date with `main`
- [x] Tests & pre-commit hooks pass
- [ ] ~Updated documentation if needed~
- [x] Updated changelog.rst if needed

## Actual checklist:
- [x] green testbank with hydrolib-core branch 569-bumping-meshkernel-version-to-latest-v300
- [x] remove mesh1d_set where possible, should be done by hydrolib-core when needed
- [x] Check amount of nodes/edges/faces in mesh1d, mesh2d and links in resulting grid. Check whether the resulting grid is not duplicated (double generated) and update hydrolib-core testbank if needed.
- [x] move hydrolib-core dependency from branch to release (https://github.com/Deltares/HYDROLIB-core/pull/574) (envs and toml)
- [x] move xugrid dependency from branch to release (https://github.com/Deltares/xugrid/pull/171) (envs and toml)

### CODE REVIEW

**Comment by xldeltares** [comment]
Hi @veenstrajelmer , I had a quick check of the PR. both the changes and the model generated seems fine.

**Comment by xldeltares** [comment]
Hi @veenstrajelmer, just found a new error from hydromt-delft3dfm python 3.9 test bench: "ImportError: cannot import name 'UnionType' from 'types')" when calling `from meshkernel.meshkernel import MeshKernel`. Do you know if that is because meshkernel does not support python 3.9 anymore?

**Review by xldeltares — APPROVED** [review]
review is OK!
